<template>
  <div class="student-page">
    <student-header :profile="profile" :logging-out="loggingOut" :homework-count="headerHomeworkCount" :order-count="headerOrderCount" :exam-count="pendingCount" @logout="handleLogout" />
    <main class="page-shell">
      <header class="page-heading"><div><p class="page-kicker">ASSESSMENT ROUTE</p><h1>我的考试</h1><p>查看班级考试安排，在入场时间内开始作答，并在成绩公布后复盘每一道题。</p></div><div class="exam-stamp"><b>{{ pendingCount }}</b><span>待完成</span></div></header>
      <div v-if="loading" class="empty-state"><strong>正在整理考试安排</strong><span>请稍候</span></div>
      <div v-else-if="errorMessage" class="error-state"><strong>考试列表暂时无法加载</strong><span>{{ errorMessage }}</span><button class="retry-button" @click="load">重新加载</button></div>
      <div v-else-if="!exams.length" class="empty-state"><strong>暂时没有考试</strong><span>老师发布班级考试后会在这里出现。</span></div>
      <section v-else class="exam-board">
        <article v-for="item in exams" :key="item.examId" :class="['exam-card', tone(item)]">
          <div class="card-index"><span>EXAM</span><b>#{{ item.examId }}</b></div>
          <div class="card-main"><div class="card-heading"><span class="status-pill">{{ statusLabel(item) }}</span><small>{{ item.totalScore }} 分</small></div><h2>{{ item.paperName }}</h2><dl><div><dt>开放时间</dt><dd>{{ formatTime(item.startTime) }}</dd></div><div><dt>最晚入场</dt><dd>{{ formatTime(item.entryDeadlineTime) }}</dd></div><div><dt>答题时长</dt><dd>{{ item.durationMinutes }} 分钟</dd></div><div><dt>整场关闭</dt><dd>{{ formatTime(item.closeTime) }}</dd></div></dl></div>
          <div class="card-action"><button v-if="item.status==='IN_PROGRESS'" @click="enter(item)">继续答题 <span>→</span></button><button v-else-if="canEnter(item)" @click="enter(item)">开始考试 <span>→</span></button><button v-else-if="item.resultVisible" class="result-button" @click="viewResult(item)">查看答卷 <span>→</span></button><p v-else>{{ actionHint(item) }}</p></div>
        </article>
      </section>
    </main>
  </div>
</template>

<script>
import StudentHeader from '@/components/StudentHeader.vue'
import studentPage from '@/mixins/studentPage'
import { listStudentExams } from '@/api/exam'
export default{name:'StudentExams',components:{StudentHeader},mixins:[studentPage],data(){return{exams:[],loading:true,errorMessage:'',now:Date.now(),timer:null}},computed:{pendingCount(){return this.exams.filter(item=>['NOT_STARTED','IN_PROGRESS'].includes(item.status)&&new Date(item.entryDeadlineTime).getTime()>=this.now).length}},mounted(){this.load();this.timer=setInterval(()=>{this.now=Date.now()},30000)},beforeDestroy(){clearInterval(this.timer)},methods:{async load(){this.loading=true;this.errorMessage='';try{const res=await listStudentExams();this.exams=Array.isArray(res.data)?res.data:[]}catch(e){this.errorMessage=e.message}finally{this.loading=false}},canEnter(item){return item.status==='NOT_STARTED'&&this.now>=new Date(item.startTime).getTime()&&this.now<=new Date(item.entryDeadlineTime).getTime()},enter(item){this.$router.push(`/exams/${item.examId}/take`)},viewResult(item){this.$router.push(`/exam-records/${item.recordId}/result`)},statusLabel(item){if(item.resultVisible)return'成绩已公布';return{NOT_STARTED:this.now<new Date(item.startTime).getTime()?'未开始':this.canEnter(item)?'可进入':'已错过',IN_PROGRESS:'答题中',SUBMITTED:'已提交',TIMEOUT:'超时提交',ABSENT:'缺考'}[item.status]||item.status},tone(item){if(item.resultVisible)return'result';if(item.status==='IN_PROGRESS')return'active';if(['SUBMITTED','TIMEOUT'].includes(item.status))return'done';if(item.status==='ABSENT')return'absent';return this.canEnter(item)?'ready':'scheduled'},actionHint(item){if(item.status==='NOT_STARTED')return this.now<new Date(item.startTime).getTime()?'考试尚未开放':'已超过最晚入场时间';if(item.status==='ABSENT')return'本场考试记为缺考';if(item.gradingStatus!=='COMPLETED')return'老师正在批改答卷';return'等待老师公布成绩'},formatTime(value){if(!value)return'-';const date=new Date(value);return Number.isNaN(date.getTime())?String(value):new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(date)}}}
</script>

<style scoped>
.exam-stamp{width:92px;height:92px;display:grid;place-content:center;border-radius:50%;color:#fff;background:var(--lagoon-deep);text-align:center}.exam-stamp b{font:800 28px var(--display)}.exam-stamp span{font-size:9px;letter-spacing:.15em}.exam-board{display:grid;gap:14px}.exam-card{min-height:170px;display:grid;grid-template-columns:105px minmax(0,1fr) 180px;overflow:hidden;border:1px solid var(--line);border-radius:8px 25px 25px 25px;background:#fff;box-shadow:var(--shadow)}.card-index{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#fff;background:var(--lagoon-deep)}.card-index span{font:700 9px var(--mono);letter-spacing:.2em;opacity:.6}.card-index b{margin-top:10px;font:800 18px var(--mono)}.card-main{padding:25px 30px}.card-heading{display:flex;align-items:center;gap:10px}.status-pill{padding:5px 8px;border-radius:999px;color:var(--lagoon-deep);background:var(--mint);font-size:9px;font-weight:700}.card-heading small{color:var(--ink-soft);font:10px var(--mono)}.card-main h2{margin-top:12px;font:750 20px var(--display)}.card-main dl{display:flex;flex-wrap:wrap;gap:18px 34px;margin-top:19px}.card-main dl div{min-width:100px}.card-main dt{color:var(--ink-soft);font-size:8px}.card-main dd{margin-top:4px;font-size:10px;font-weight:650}.card-action{display:grid;place-content:center;padding:20px;background:var(--sky);text-align:center}.card-action button{min-width:130px;padding:12px 15px;border:0;border-radius:10px;color:#fff;background:var(--lagoon);font-size:11px;font-weight:700}.card-action button span{margin-left:10px}.card-action .result-button{background:var(--coral)}.card-action p{max-width:130px;color:var(--ink-soft);font-size:10px;line-height:1.7}.exam-card.active .card-index{background:var(--coral)}.exam-card.done,.exam-card.scheduled{opacity:.82}.exam-card.absent{filter:grayscale(.65)}.exam-card.result{border-color:rgba(255,122,89,.4)}
@media(max-width:800px){.exam-card{grid-template-columns:70px 1fr}.card-action{grid-column:1/-1}.card-main{padding:20px}.card-main dl{display:grid;grid-template-columns:1fr 1fr}}
</style>
