<template>
  <div class="exam-page page-container">
    <header class="page-head"><div><p class="eyebrow">EXAM · LIVE LEDGER</p><h1>考试管理</h1><p class="subcopy">发布考试、跟踪考生状态、批改主观题并控制成绩公布。</p></div><el-button type="primary" icon="el-icon-s-promotion" @click="publishVisible=true">发布考试</el-button></header>
    <section class="search-bar"><el-form :inline="true" :model="query"><el-form-item label="试卷"><el-select v-model="query.paperId" clearable filterable><el-option v-for="item in papers" :key="item.id" :label="item.paperName" :value="item.id" /></el-select></el-form-item><el-form-item label="班级"><el-select v-model="query.classId" clearable filterable><el-option v-for="item in classes" :key="item.id" :label="item.classPeriod" :value="item.id" /></el-select></el-form-item><el-form-item><el-button type="primary" icon="el-icon-search" @click="search">查询</el-button></el-form-item></el-form></section>
    <section class="table-card"><el-table v-loading="loading" :data="records" stripe row-key="id"><el-table-column prop="id" label="ID" width="70" /><el-table-column label="考试"><template slot-scope="scope"><div class="exam-title"><b>{{ scope.row.paperName }}</b><small>{{ scope.row.className }}</small></div></template></el-table-column><el-table-column label="时间窗口" min-width="240"><template slot-scope="scope"><div class="time-window"><span>开放 {{ formatTime(scope.row.startTime) }}</span><span>入场截止 {{ formatTime(scope.row.entryDeadlineTime) }}</span><span>整场关闭 {{ formatTime(scope.row.closeTime) }}</span></div></template></el-table-column><el-table-column label="时长" width="75"><template slot-scope="scope">{{ scope.row.durationMinutes }} 分</template></el-table-column><el-table-column label="状态" width="90"><template slot-scope="scope"><el-tag size="small" :type="scope.row.lifecycle==='OPEN'?'success':scope.row.lifecycle==='CLOSED'?'info':'warning'">{{ lifecycleLabel(scope.row.lifecycle) }}</el-tag></template></el-table-column><el-table-column label="考生进度" min-width="240"><template slot-scope="scope"><div class="progress-strip"><span>待考 {{ scope.row.notStartedCount }}</span><span>作答 {{ scope.row.inProgressCount }}</span><span>提交 {{ scope.row.submittedCount + scope.row.timeoutCount }}</span><span>缺考 {{ scope.row.absentCount }}</span></div></template></el-table-column><el-table-column label="公布" width="90"><template slot-scope="scope"><el-switch :value="scope.row.answerVisible" @change="value => changeVisibility(scope.row,value)" /></template></el-table-column><el-table-column label="操作" width="120"><template slot-scope="scope"><el-button type="text" @click="openRecords(scope.row)">考生与批改</el-button></template></el-table-column></el-table><div class="pagination-wrapper"><el-pagination background layout="total, sizes, prev, pager, next" :total="total" :current-page="query.current" :page-size="query.size" @current-change="page=>{query.current=page;load()}" @size-change="size=>{query.size=size;query.current=1;load()}" /></div></section>

    <el-dialog title="发布考试" :visible.sync="publishVisible" width="620px" append-to-body><el-form :model="publishForm" label-width="110px"><el-form-item label="试卷"><el-select v-model="publishForm.paperId" filterable style="width:100%"><el-option v-for="item in papers.filter(p=>p.status!=='ARCHIVED')" :key="item.id" :label="`${item.paperName} · ${item.totalScore}分`" :value="item.id" /></el-select></el-form-item><el-form-item label="发布班级"><el-select v-model="publishForm.classIds" multiple filterable style="width:100%"><el-option v-for="item in compatibleClasses" :key="item.id" :label="item.classPeriod" :value="item.id" /></el-select></el-form-item><el-form-item label="开始时间"><el-date-picker v-model="publishForm.startTime" type="datetime" value-format="yyyy-MM-ddTHH:mm:ss" style="width:100%" /></el-form-item><el-form-item label="最晚入场"><el-date-picker v-model="publishForm.entryDeadlineTime" type="datetime" value-format="yyyy-MM-ddTHH:mm:ss" style="width:100%" /></el-form-item><el-form-item label="考试时长"><el-input-number v-model="publishForm.durationMinutes" :min="1" :max="1440" /> 分钟</el-form-item><div class="close-preview"><span>预计整场关闭</span><b>{{ closePreview }}</b><small>在最晚入场前进入的学生都拥有完整答题时长</small></div></el-form><span slot="footer"><el-button @click="publishVisible=false">取消</el-button><el-button type="primary" :loading="publishing" @click="submitPublish">确认发布</el-button></span></el-dialog>

    <el-dialog :title="activeExam ? `${activeExam.paperName} · ${activeExam.className}` : '考生记录'" :visible.sync="recordVisible" width="900px" append-to-body><div class="record-filter"><el-input v-model.trim="recordQuery.studentKeyword" clearable placeholder="学生姓名" /><el-select v-model="recordQuery.status" clearable placeholder="作答状态"><el-option v-for="item in recordStatuses" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-select v-model="recordQuery.gradingStatus" clearable placeholder="批改状态"><el-option label="待批改" value="PENDING" /><el-option label="批改中" value="GRADING" /><el-option label="已完成" value="COMPLETED" /></el-select><el-button type="primary" @click="loadRecords">筛选</el-button></div><el-table v-loading="recordLoading" :data="studentRecords"><el-table-column prop="studentName" label="学生" /><el-table-column label="作答状态"><template slot-scope="scope"><el-tag size="small">{{ recordStatusLabel(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="批改状态"><template slot-scope="scope">{{ gradingLabel(scope.row.gradingStatus) }}</template></el-table-column><el-table-column label="提交时间"><template slot-scope="scope">{{ formatTime(scope.row.submitTime) }}</template></el-table-column><el-table-column label="成绩"><template slot-scope="scope">{{ scope.row.score == null ? '-' : scope.row.score }}</template></el-table-column><el-table-column label="操作"><template slot-scope="scope"><el-button v-if="['SUBMITTED','TIMEOUT'].includes(scope.row.status)" type="text" @click="openGrading(scope.row)">批改</el-button></template></el-table-column></el-table><div class="pagination-wrapper"><el-pagination small layout="total, prev, pager, next" :total="recordTotal" :current-page="recordQuery.current" :page-size="recordQuery.size" @current-change="page=>{recordQuery.current=page;loadRecords()}" /></div></el-dialog>

    <el-dialog title="主观题批改" :visible.sync="gradingVisible" width="780px" append-to-body><div v-if="gradingData" class="grading-sheet"><header><b>{{ gradingData.record.studentName }}</b><span>客观题 {{ gradingData.record.objectiveScore }} 分</span></header><article v-for="(item,index) in gradingData.answers" :key="item.answerId"><h3>{{ index+1 }}. {{ item.questionContent }} <span>{{ item.maxScore }}分</span></h3><div class="answer-box"><small>学生答案</small><p>{{ item.studentAnswer || '未作答' }}</p></div><div class="reference"><small>参考答案</small><p>{{ item.referenceAnswer }}</p></div><div class="grade-row"><el-input-number v-model="item.score" :min="0" :max="Number(item.maxScore)" :precision="1" /><el-input v-model="item.graderComment" placeholder="批改评语（可选）" /></div></article></div><span slot="footer"><el-button @click="gradingVisible=false">取消</el-button><el-button type="primary" :loading="gradingSaving" @click="saveGrading">保存批改</el-button></span></el-dialog>
  </div>
</template>

<script>
import { pageClass } from '@/api/class'
import { pageExamPapers, pageExams, publishExam, pageExamRecords, updateExamVisibility, getExamGrading, saveExamGrading } from '@/api/exam'
export default{name:'ExamManage',data(){return{loading:false,publishing:false,recordLoading:false,gradingSaving:false,publishVisible:false,recordVisible:false,gradingVisible:false,records:[],total:0,papers:[],classes:[],activeExam:null,studentRecords:[],recordTotal:0,gradingData:null,query:{current:1,size:10,paperId:null,classId:null},publishForm:{paperId:null,classIds:[],startTime:'',entryDeadlineTime:'',durationMinutes:60},recordQuery:{current:1,size:10,studentKeyword:'',status:'',gradingStatus:''},recordStatuses:[{value:'NOT_STARTED',label:'待考'},{value:'IN_PROGRESS',label:'作答中'},{value:'SUBMITTED',label:'已提交'},{value:'TIMEOUT',label:'超时提交'},{value:'ABSENT',label:'缺考'}]}},computed:{compatibleClasses(){const paper=this.papers.find(item=>item.id===this.publishForm.paperId);return paper?this.classes.filter(item=>item.courseId===paper.courseId):this.classes},closePreview(){if(!this.publishForm.entryDeadlineTime)return '待设置';const date=new Date(this.publishForm.entryDeadlineTime);if(Number.isNaN(date.getTime()))return '待设置';date.setMinutes(date.getMinutes()+Number(this.publishForm.durationMinutes||0));return this.formatTime(date)},},mounted(){this.loadOptions();this.load()},methods:{
 async loadOptions(){const[papers,classes]=await Promise.all([pageExamPapers({current:1,size:100}),pageClass({current:1,size:100})]);this.papers=(papers.data&&papers.data.records)||[];this.classes=(classes.data&&classes.data.records)||[]},async load(){this.loading=true;try{const res=await pageExams(this.query);this.records=(res.data&&res.data.records)||[];this.total=(res.data&&res.data.total)||0}finally{this.loading=false}},search(){this.query.current=1;this.load()},async submitPublish(){if(!this.publishForm.paperId||!this.publishForm.classIds.length||!this.publishForm.startTime||!this.publishForm.entryDeadlineTime)return this.$message.warning('请完整填写发布信息');this.publishing=true;try{await publishExam(this.publishForm);this.$message.success('考试已发布');this.publishVisible=false;this.publishForm={paperId:null,classIds:[],startTime:'',entryDeadlineTime:'',durationMinutes:60};await Promise.all([this.load(),this.loadOptions()])}finally{this.publishing=false}},async changeVisibility(row,value){try{await updateExamVisibility(row.id,value);this.$message.success(value?'成绩已公布':'成绩已隐藏');this.load()}catch(e){this.load()}},openRecords(row){this.activeExam=row;this.recordQuery={current:1,size:10,studentKeyword:'',status:'',gradingStatus:''};this.recordVisible=true;this.loadRecords()},async loadRecords(){if(!this.activeExam)return;this.recordLoading=true;try{const res=await pageExamRecords(this.activeExam.id,this.recordQuery);this.studentRecords=(res.data&&res.data.records)||[];this.recordTotal=(res.data&&res.data.total)||0}finally{this.recordLoading=false}},async openGrading(row){const res=await getExamGrading(row.id);this.gradingData=res.data;this.gradingData.answers.forEach(item=>{if(item.score==null)this.$set(item,'score',0);if(item.graderComment==null)this.$set(item,'graderComment','')});this.gradingVisible=true},async saveGrading(){this.gradingSaving=true;try{await saveExamGrading(this.gradingData.record.id,{answers:this.gradingData.answers.map(item=>({answerId:item.answerId,score:item.score,comment:item.graderComment}))});this.$message.success('批改已保存');this.gradingVisible=false;this.loadRecords();this.load()}finally{this.gradingSaving=false}},formatTime(value){if(!value)return '-';const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?String(value).replace('T',' ').slice(0,16):new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(date)},lifecycleLabel(v){return{SCHEDULED:'待开始',OPEN:'进行窗口',CLOSED:'已关闭'}[v]||v},recordStatusLabel(v){const item=this.recordStatuses.find(s=>s.value===v);return item?item.label:v},gradingLabel(v){return{PENDING:'待批改',GRADING:'批改中',COMPLETED:'已完成'}[v]||v}
}}
</script>

<style scoped>
.subcopy{margin-top:8px;color:var(--ink-3);font-size:13px}.exam-title,.time-window{display:flex;flex-direction:column;gap:5px}.exam-title small,.time-window{color:var(--ink-3);font-size:11px}.progress-strip{display:flex;gap:5px;flex-wrap:wrap}.progress-strip span{padding:4px 7px;border-radius:4px;background:#F0F4EF;color:var(--ink-2);font-size:10px}.close-preview{margin-left:110px;padding:14px 16px;border-left:3px solid var(--brass);background:#F8FAF7}.close-preview span,.close-preview small{display:block;color:var(--ink-3);font-size:10px}.close-preview b{display:block;margin:6px 0;font:700 17px var(--font-mono)}.record-filter{display:grid;grid-template-columns:1fr 150px 150px auto;gap:8px;margin-bottom:14px}.grading-sheet>header{display:flex;justify-content:space-between;padding:14px 16px;color:#fff;background:var(--pine);border-radius:8px}.grading-sheet article{padding:18px 0;border-bottom:1px solid var(--line)}.grading-sheet h3{font-size:14px;line-height:1.7}.grading-sheet h3 span{float:right;color:var(--brass-ink)}.answer-box,.reference{margin-top:10px;padding:11px 13px;border-radius:7px;background:#F5F7F3}.reference{background:var(--jade-soft)}.answer-box small,.reference small{color:var(--ink-3);font-size:9px}.answer-box p,.reference p{margin-top:5px;line-height:1.7}.grade-row{display:grid;grid-template-columns:150px 1fr;gap:10px;margin-top:12px}@media(max-width:760px){.record-filter{grid-template-columns:1fr}.close-preview{margin-left:0}}
</style>
