<template>
  <div class="paper-page page-container">
    <header class="page-head"><div><p class="eyebrow">EXAM · PAPER STUDIO</p><h1>试卷管理</h1><p class="subcopy">从课程阶段题库中挑选题目，编排分值与答题顺序。</p></div><el-button type="primary" icon="el-icon-plus" @click="openCreate">新增试卷</el-button></header>
    <section class="search-bar"><el-form :inline="true" :model="query"><el-form-item label="试卷名称"><el-input v-model.trim="query.keyword" clearable @keyup.enter.native="search" /></el-form-item><el-form-item label="课程"><el-select v-model="query.courseId" clearable filterable><el-option v-for="item in courses" :key="item.id" :label="item.courseName" :value="item.id" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option label="草稿" value="DRAFT" /><el-option label="已锁定" value="LOCKED" /><el-option label="已归档" value="ARCHIVED" /></el-select></el-form-item><el-form-item><el-button type="primary" icon="el-icon-search" @click="search">查询</el-button></el-form-item></el-form></section>
    <section class="table-card"><el-table v-loading="loading" :data="records" stripe row-key="id"><el-table-column prop="id" label="ID" width="72" /><el-table-column label="试卷"><template slot-scope="scope"><div class="paper-name"><b>{{ scope.row.paperName }}</b><small>{{ courseName(scope.row.courseId) }}</small></div></template></el-table-column><el-table-column label="覆盖阶段" min-width="220"><template slot-scope="scope"><div class="tags"><el-tag v-for="stage in scope.row.stageNames" :key="stage" size="small" type="info">{{ stage }}</el-tag></div></template></el-table-column><el-table-column label="题目" width="80"><template slot-scope="scope"><span class="mono">{{ scope.row.questions.length }}</span></template></el-table-column><el-table-column label="总分" width="90"><template slot-scope="scope"><b class="score">{{ scope.row.totalScore }}</b></template></el-table-column><el-table-column label="状态" width="100"><template slot-scope="scope"><el-tag :type="scope.row.status === 'DRAFT' ? 'warning' : scope.row.status === 'LOCKED' ? 'success' : 'info'" size="small">{{ paperStatus(scope.row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="170"><template slot-scope="scope"><el-button type="text" @click="preview(scope.row)">详情</el-button><el-button v-if="scope.row.status === 'DRAFT'" type="text" @click="openEdit(scope.row)">编辑</el-button></template></el-table-column></el-table><div class="pagination-wrapper"><el-pagination background layout="total, sizes, prev, pager, next" :total="total" :current-page="query.current" :page-size="query.size" @current-change="page => { query.current=page; load() }" @size-change="size => { query.size=size; query.current=1; load() }" /></div></section>

    <el-dialog :title="form.id ? '编辑试卷草稿' : '创建试卷'" :visible.sync="builderVisible" width="94%" top="4vh" append-to-body @closed="resetBuilder">
      <div class="paper-meta"><el-input v-model="form.paperName" placeholder="试卷名称" /><el-select v-model="form.courseId" filterable placeholder="选择课程" @change="handleCourseChange"><el-option v-for="item in courses" :key="item.id" :label="item.courseName" :value="item.id" /></el-select><el-select v-model="form.stageNames" multiple filterable placeholder="覆盖阶段"><el-option v-for="stage in availableStages" :key="stage" :label="stage" :value="stage" /></el-select><div class="total-seal"><span>总分</span><b>{{ totalScore }}</b></div></div>
      <div class="paper-workbench">
        <section class="candidate-shelf"><header><div><p>CANDIDATE SHELF</p><h3>候选题架</h3></div><el-button size="mini" icon="el-icon-refresh" @click="loadCandidates">刷新</el-button></header><div class="candidate-filter"><el-select v-model="candidateQuery.stageName" clearable placeholder="阶段"><el-option v-for="stage in form.stageNames" :key="stage" :label="stage" :value="stage" /></el-select><el-select v-model="candidateQuery.questionType" clearable placeholder="题型"><el-option v-for="item in typeOptions" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-select v-model="candidateQuery.difficulty" clearable placeholder="难度"><el-option label="简单" value="EASY" /><el-option label="普通" value="NORMAL" /><el-option label="困难" value="HARD" /></el-select><el-button type="primary" size="small" @click="loadCandidates">筛选</el-button></div><div class="candidate-list" v-loading="candidateLoading"><article v-for="item in candidates" :key="item.id" :class="{ chosen: selectedIds.includes(item.id) }"><div><span>{{ typeLabel(item.questionType) }} · {{ difficultyLabel(item.difficulty) }}</span><b>{{ item.questionContent }}</b><small>{{ item.options.map(o => `${o.optionKey}.${o.optionContent}`).join('　') }}</small></div><el-button size="mini" :disabled="selectedIds.includes(item.id)" @click="addQuestion(item)">加入</el-button></article><el-empty v-if="!candidateLoading && !candidates.length" description="先选择课程和阶段，再筛选题目" /></div></section>
        <section class="paper-outline"><header><div><p>PAPER OUTLINE</p><h3>试卷结构</h3></div><span>{{ form.questions.length }} 题</span></header><div class="outline-list"><article v-for="(item,index) in form.questions" :key="item.questionId"><span class="order">{{ index + 1 }}</span><div><small>{{ typeLabel(item.questionType) }}</small><b>{{ item.questionContent }}</b></div><el-input-number v-model="item.questionScore" :min="0.1" :step="1" :precision="1" size="mini" /><el-button type="text" class="danger-link" icon="el-icon-delete" @click="form.questions.splice(index,1)" /></article><el-empty v-if="!form.questions.length" description="从左侧加入题目" /></div></section>
      </div>
      <span slot="footer"><el-button @click="builderVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="savePaper">保存试卷</el-button></span>
    </el-dialog>

    <el-dialog title="试卷详情" :visible.sync="previewVisible" width="760px" append-to-body><div v-if="previewPaper" class="preview-paper"><header><div><p>{{ courseName(previewPaper.courseId) }} · {{ previewPaper.stageNames.join(' / ') }}</p><h2>{{ previewPaper.paperName }}</h2></div><b>{{ previewPaper.totalScore }} 分</b></header><article v-for="(item,index) in previewPaper.questions" :key="item.id"><h3>{{ index + 1 }}. {{ item.questionContent }} <span>{{ item.questionScore }}分</span></h3><p v-for="option in item.options" :key="option.id">{{ option.optionKey }}. {{ option.optionContent }}</p><small>答案：{{ item.answerContent }}</small></article></div></el-dialog>
  </div>
</template>

<script>
import { pageCourse } from '@/api/course'
import { pageCourseDetail } from '@/api/courseDetail'
import { pageExamQuestions, pageExamPapers, createExamPaper, updateExamPaper } from '@/api/exam'
const emptyForm = () => ({ id:null, paperName:'', courseId:null, stageNames:[], questions:[] })
export default { name:'PaperManage', data(){return{loading:false,saving:false,candidateLoading:false,builderVisible:false,previewVisible:false,previewPaper:null,records:[],total:0,courses:[],availableStages:[],candidates:[],query:{current:1,size:10,keyword:'',courseId:null,status:''},candidateQuery:{stageName:'',questionType:'',difficulty:''},form:emptyForm(),typeOptions:[{value:'SINGLE',label:'单选题'},{value:'MULTIPLE',label:'多选题'},{value:'JUDGE',label:'判断题'},{value:'FILL',label:'填空题'},{value:'SHORT',label:'简答题'}]}}, computed:{totalScore(){return this.form.questions.reduce((sum,item)=>sum+Number(item.questionScore||0),0).toFixed(1)},selectedIds(){return this.form.questions.map(item=>item.questionId)}}, mounted(){this.loadCourses();this.load()}, methods:{
    async loadCourses(){const res=await pageCourse({current:1,size:100});this.courses=(res.data&&res.data.records)||[]},
    async load(){this.loading=true;try{const res=await pageExamPapers(this.query);this.records=(res.data&&res.data.records)||[];this.total=(res.data&&res.data.total)||0}finally{this.loading=false}}, search(){this.query.current=1;this.load()},
    openCreate(){this.form=emptyForm();this.candidates=[];this.builderVisible=true},
    async openEdit(row){this.form={id:row.id,paperName:row.paperName,courseId:row.courseId,stageNames:[...row.stageNames],questions:row.questions.map((item,index)=>({questionId:item.questionId,questionType:item.questionType,questionContent:item.questionContent,questionScore:Number(item.questionScore),sortOrder:index}))};await this.handleCourseChange(row.courseId,false);this.builderVisible=true;this.loadCandidates()},
    preview(row){this.previewPaper=row;this.previewVisible=true},
    async handleCourseChange(courseId,clear=true){if(clear){this.form.stageNames=[];this.form.questions=[]}if(!courseId){this.availableStages=[];return}const res=await pageCourseDetail({current:1,size:100,courseId});const rows=(res.data&&res.data.records)||[];this.availableStages=[...new Set(rows.map(item=>item.stageName).filter(Boolean))]},
    async loadCandidates(){if(!this.form.courseId||!this.form.stageNames.length){this.candidates=[];return this.$message.warning('请先选择课程和覆盖阶段')}this.candidateLoading=true;try{const params={current:1,size:100,courseId:this.form.courseId,stageName:this.candidateQuery.stageName||undefined,questionType:this.candidateQuery.questionType||undefined,difficulty:this.candidateQuery.difficulty||undefined,status:'ENABLED'};const res=await pageExamQuestions(params);this.candidates=(res.data&&res.data.records)||[]}finally{this.candidateLoading=false}},
    addQuestion(item){this.form.questions.push({questionId:item.id,questionType:item.questionType,questionContent:item.questionContent,questionScore:5,sortOrder:this.form.questions.length})},
    async savePaper(){if(!this.form.paperName.trim())return this.$message.warning('请输入试卷名称');if(!this.form.courseId||!this.form.stageNames.length)return this.$message.warning('请选择课程阶段');if(!this.form.questions.length)return this.$message.warning('请至少加入一道题');this.saving=true;try{const data={paperName:this.form.paperName.trim(),courseId:this.form.courseId,stageNames:this.form.stageNames,questions:this.form.questions.map((item,index)=>({questionId:item.questionId,questionScore:item.questionScore,sortOrder:index}))};this.form.id?await updateExamPaper(this.form.id,data):await createExamPaper(data);this.$message.success('试卷已保存');this.builderVisible=false;this.load()}finally{this.saving=false}},
    resetBuilder(){this.form=emptyForm();this.candidates=[];this.availableStages=[];this.candidateQuery={stageName:'',questionType:'',difficulty:''}},courseName(id){const item=this.courses.find(course=>course.id===id);return item?item.courseName:`课程 #${id}`},typeLabel(value){const item=this.typeOptions.find(type=>type.value===value);return item?item.label:value},difficultyLabel(value){return{EASY:'简单',NORMAL:'普通',HARD:'困难'}[value]||value},paperStatus(value){return{DRAFT:'草稿',LOCKED:'已锁定',ARCHIVED:'已归档'}[value]||value}
  }}
</script>

<style scoped>
.subcopy{margin-top:8px;color:var(--ink-3);font-size:13px}.paper-name{display:flex;flex-direction:column;gap:5px}.paper-name small{color:var(--ink-3)}.tags{display:flex;gap:5px;flex-wrap:wrap}.score{font:700 17px var(--font-mono);color:var(--jade-deep)}.paper-meta{display:grid;grid-template-columns:1.2fr 1fr 1.5fr 90px;gap:12px;margin-bottom:16px}.total-seal{display:grid;place-content:center;text-align:center;border-radius:8px;color:#fff;background:var(--pine)}.total-seal span{font-size:9px;letter-spacing:.16em}.total-seal b{font:700 22px var(--font-mono)}.paper-workbench{height:62vh;display:grid;grid-template-columns:1fr 1fr;gap:16px}.candidate-shelf,.paper-outline{min-width:0;display:flex;flex-direction:column;overflow:hidden;border:1px solid var(--line);border-radius:9px;background:#F8FAF7}.candidate-shelf>header,.paper-outline>header{display:flex;align-items:center;justify-content:space-between;padding:15px 18px;border-bottom:1px solid var(--line);background:#fff}.candidate-shelf header p,.paper-outline header p{color:var(--brass-ink);font:700 8px var(--font-mono);letter-spacing:.18em}.candidate-shelf h3,.paper-outline h3{margin-top:4px}.candidate-filter{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:7px;padding:10px}.candidate-list,.outline-list{min-height:0;overflow:auto;padding:10px;display:grid;align-content:start;gap:8px}.candidate-list article,.outline-list article{display:flex;align-items:center;gap:12px;padding:13px;border:1px solid var(--line-soft);border-radius:8px;background:#fff}.candidate-list article.chosen{opacity:.52}.candidate-list article>div,.outline-list article>div{min-width:0;flex:1;display:flex;flex-direction:column;gap:5px}.candidate-list span,.outline-list small{color:var(--brass-ink);font-size:9px}.candidate-list b,.outline-list b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.candidate-list small{overflow:hidden;color:var(--ink-3);font-size:9px;text-overflow:ellipsis;white-space:nowrap}.order{width:28px;height:28px;display:grid;place-items:center;flex:none;border-radius:50%;color:#fff;background:var(--jade);font:700 11px var(--font-mono)}.preview-paper header{display:flex;justify-content:space-between;padding-bottom:18px;border-bottom:2px solid var(--ink)}.preview-paper header p{color:var(--ink-3);font-size:11px}.preview-paper header h2{margin-top:6px}.preview-paper header>b{font:700 22px var(--font-mono)}.preview-paper article{padding:17px 0;border-bottom:1px solid var(--line)}.preview-paper article h3{font-size:14px;line-height:1.7}.preview-paper article h3 span{float:right;color:var(--brass-ink)}.preview-paper article p{margin:7px 0 0 20px}.preview-paper article small{display:block;margin-top:10px;color:var(--jade-deep)}.danger-link{color:var(--clay)}
@media(max-width:1000px){.paper-meta{grid-template-columns:1fr 1fr}.paper-workbench{height:auto;grid-template-columns:1fr}.candidate-shelf,.paper-outline{height:480px}}
</style>
